INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/file HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
2025-05-25 22:47:33,995 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 22:47:34,001 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
INFO:     127.0.0.1:61288 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/file HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /static/js/file.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:61288 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/list_dir?path=calculate HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/file HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61288 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61289 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61350 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61350 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61350 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
2025-05-25 22:54:24,029 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 22:54:24,029 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 22:54:24,029 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
2025-05-25 22:54:24,029 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
INFO:     127.0.0.1:61765 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61765 - "GET /static/js/log.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:61766 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61766 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61773 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
WatchFiles detected changes in 'config.py'. Reloading...
 
2025-05-25 22:57:17,306 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 22:57:17,306 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 22:57:17,310 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 22:57:17,310 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 22:57:17,315 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 22:57:17,315 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 69, in serve
    with self.capture_signals():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 699, in lifespan
    await receive()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 69, in serve
    with self.capture_signals():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 699, in lifespan
    await receive()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2025-05-25 22:57:18,367 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 22:57:18,367 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 22:57:18,374 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
2025-05-25 22:57:18,374 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
INFO:     127.0.0.1:61968 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61968 - "GET /static/style.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:61969 - "GET /admin/file HTTP/1.1" 200 OK
INFO:     127.0.0.1:61969 - "GET /static/js/file.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:61969 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:61969 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61977 - "GET /admin/file HTTP/1.1" 200 OK
INFO:     127.0.0.1:61977 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:61977 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/file HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /static/js/sysinfo.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:61982 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/log HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/file HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:61982 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
2025-05-25 23:02:20,803 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:02:20,803 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:02:20,807 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:02:20,807 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:02:20,810 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:02:20,810 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 69, in serve
    with self.capture_signals():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 699, in lifespan
    await receive()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 69, in serve
    with self.capture_signals():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 699, in lifespan
    await receive()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2025-05-25 23:02:20,824 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:02:20,824 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:02:20,826 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:02:20,826 - utils.logger - INFO - Log stream WebSocket disconnected or cancelled.
2025-05-25 23:07:38,166 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 23:07:38,166 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 23:07:38,166 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
2025-05-25 23:07:38,166 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
INFO:     127.0.0.1:62669 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62669 - "GET /static/logo.svg HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:62668 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /static/js/apidebug.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:62668 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /admin/get_function_file_content/cs?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62668 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62680 - "GET /admin/file HTTP/1.1" 200 OK
INFO:     127.0.0.1:62680 - "GET /static/js/file.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:62680 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
INFO:     127.0.0.1:62680 - "DELETE /admin/delete_file?path=cs HTTP/1.1" 200 OK
INFO:     127.0.0.1:62680 - "GET /admin/list_dir?path= HTTP/1.1" 200 OK
WatchFiles detected changes in 'apps\cs\function.py'. Reloading...
 
2025-05-25 23:07:58,662 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 23:07:58,662 - utils.logger - INFO - Checking dependencies on startup...
2025-05-25 23:07:58,668 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
2025-05-25 23:07:58,668 - utils.logger - INFO - Installed new dependencies on startup: {'status': 'success', 'message': '依赖环境检查完成', 'new_deps': [], 'conflicts': []}
INFO:     127.0.0.1:62704 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62704 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /functions HTTP/1.1" 200 OK
2025-05-25 23:08:26,635 - utils.logger - ERROR - Unhandled error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\admin\Desktop\new\main.py", line 241, in error_handling_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\main.py", line 128, in add_process_time_header
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\trustedhost.py", line 36, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\admin\admin.py", line 709, in call_stats_data
    stats = json.load(f)
            ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-05-25 23:08:26,635 - utils.logger - ERROR - Unhandled error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\admin\Desktop\new\main.py", line 241, in error_handling_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\main.py", line 128, in add_process_time_header
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\trustedhost.py", line 36, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\admin\admin.py", line 709, in call_stats_data
    stats = json.load(f)
            ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:62705 - "GET /admin/call_stats_data HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:62705 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
2025-05-25 23:08:30,899 - utils.logger - INFO - Calling function: calculate
2025-05-25 23:08:30,899 - utils.logger - INFO - Calling function: calculate
2025-05-25 23:08:30,899 - utils.logger - ERROR - Error updating call stats: Expecting value: line 1 column 1 (char 0)
2025-05-25 23:08:30,899 - utils.logger - ERROR - Error updating call stats: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:62705 - "GET /function/calculate?num1=0&num2=0&operation=add HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /functions HTTP/1.1" 200 OK
2025-05-25 23:08:32,411 - utils.logger - ERROR - Unhandled error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\admin\Desktop\new\main.py", line 241, in error_handling_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\main.py", line 128, in add_process_time_header
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\trustedhost.py", line 36, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\admin\admin.py", line 709, in call_stats_data
    stats = json.load(f)
            ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-05-25 23:08:32,411 - utils.logger - ERROR - Unhandled error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\admin\Desktop\new\main.py", line 241, in error_handling_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\main.py", line 128, in add_process_time_header
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\trustedhost.py", line 36, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\admin\admin.py", line 709, in call_stats_data
    stats = json.load(f)
            ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:62705 - "GET /admin/call_stats_data HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:62705 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62705 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
2025-05-25 23:08:43,797 - utils.logger - INFO - Calling function: calculate
2025-05-25 23:08:43,797 - utils.logger - INFO - Calling function: calculate
2025-05-25 23:08:43,799 - utils.logger - ERROR - Error updating call stats: Expecting value: line 1 column 1 (char 0)
2025-05-25 23:08:43,799 - utils.logger - ERROR - Error updating call stats: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:62732 - "GET /function/calculate?num1=0&num2=0&operation=add HTTP/1.1" 200 OK
INFO:     127.0.0.1:62732 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62732 - "GET /functions HTTP/1.1" 200 OK
2025-05-25 23:08:45,356 - utils.logger - ERROR - Unhandled error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\admin\Desktop\new\main.py", line 241, in error_handling_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\main.py", line 128, in add_process_time_header
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\trustedhost.py", line 36, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\admin\admin.py", line 709, in call_stats_data
    stats = json.load(f)
            ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-05-25 23:08:45,356 - utils.logger - ERROR - Unhandled error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\Users\admin\Desktop\new\main.py", line 241, in error_handling_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\main.py", line 128, in add_process_time_header
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\trustedhost.py", line 36, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\admin\Desktop\new\admin\admin.py", line 709, in call_stats_data
    stats = json.load(f)
            ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:62732 - "GET /admin/call_stats_data HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:62834 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/apidebug HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/get_function_file_content/calculate?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/get_function_file_content/echo_message?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/get_function_file_content/example_function?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/get_function_file_content/functions?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/get_function_file_content/get_random_xlsx_line?file_path=config.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/get_function_file_content/hello_world?file_path=config.json HTTP/1.1" 200 OK
2025-05-25 23:10:03,130 - utils.logger - INFO - Calling function: calculate
2025-05-25 23:10:03,130 - utils.logger - INFO - Calling function: calculate
INFO:     127.0.0.1:62834 - "GET /function/calculate?num1=0&num2=0&operation=add HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62834 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
INFO:     127.0.0.1:62833 - "GET /admin/sysinfo HTTP/1.1" 200 OK
INFO:     127.0.0.1:62833 - "GET /functions HTTP/1.1" 200 OK
INFO:     127.0.0.1:62833 - "GET /admin/call_stats_data HTTP/1.1" 200 OK
